### ISSUE TITLE
SHAudioPlayerSDK error with xcode 11.1

### ISSUE THREAD

**Issue by DGP13** [shebinkoshy/SHAudioPlayer#1]
Could not find module 'SHAudioPlayerSDK' for target 'arm64-apple-ios'; found: x86_64

**Comment by shebinkoshy** [comment]
@DGP13 Can you try `xcode11.1` branch. 

If you are running in real device, you have to replace the `SHAudioPlayerSDK.framework` in project root directory with `SDK/Device/SHAudioPlayerSDK.framework`

**Comment by shebinkoshy** [comment]
Please let us know, If are you facing any issues.

**Comment by ghost** [comment]
I am facing same issue after replacing the framework. Could not find module 'SHAudioPlayerSDK' for architecture 'arm64'; found: x86_64

**Comment by shebinkoshy** [comment]
@Sagar021 can you please give more details
Xcode version?
Simulator or real device?
Device/simulator model?
iOS version?
