### ISSUE TITLE
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.3

### ISSUE THREAD

**Issue by SimonFernandes7** [shebinkoshy/SHAudioPlayer#2]
Hi, I'm facing issues to run and check your code in the latest Swift version. Requesting you to set BUILD_LIBRARY_FOR_DISTRIBUTION = YES in your framework.

Source: https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler

Thanks in advance.

**Comment by shebinkoshy** [comment]
@SimonFernandes7 Thanks for addressing the issue. Fix is available, please clone the latest.
